
---
AWSTemplateFormatVersion: '2010-09-09'
Description: default SPA Atom

Parameters:
  awsAccountId:
    Type: String
    Default: "false"
  cloudformationsBucket:
    Type: String
    Default: "false"
  deploymentStage:
    Type: String
    Default: dev

Resources:

  role:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["", ["https://s3.amazonaws.com/deploy-forms-larkin", "/forms/resources/role.yaml"]]
      TimeoutInMinutes: 2
      Parameters:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Join ["", ["s3://",!Ref cloudformationsBucket, "/microservice-template/awsoptions/role.yaml"]]

  api:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["", ["https://s3.amazonaws.com/deploy-forms-larkin", "/forms/resources/api.yaml"]]
      TimeoutInMinutes: 2
      Parameters:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Join ["", ["s3://",!Ref cloudformationsBucket, "/microservice-template/awsoptions/api.yaml"]]

Outputs:
  roleName:
    Value:
      Fn::GetAtt: [role, Outputs.roleName]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-roleName
  roleArn:
    Value:
      Fn::GetAtt: [role, Outputs.roleArn]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-roleArn
  apiRootResourceId:
    Value:
      Fn::GetAtt: [api, Outputs.apiRootResourceId]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-apiRootResourceId
  apiId:
    Value:
      Fn::GetAtt: [api, Outputs.apiId]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-apiId
  apiResourceId:
    Value:
      Fn::GetAtt: [api, Outputs.apiResourceId]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-apiResourceId
  apiMethodId:
    Value:
      Fn::GetAtt: [api, Outputs.apiMethodId]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-apiMethodId
  gitHubProjectName:
    Value:
      Fn::GetAtt: [codebuild, Outputs.gitHubProjectName]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-gitHubProjectName
  gitHubRepoUrl:
    Value:
      Fn::GetAtt: [codebuild, Outputs.gitHubRepoUrl]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-gitHubRepoUrl
  gitHubRepoName:
    Value:
      Fn::GetAtt: [codebuild, Outputs.gitHubRepoName]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-gitHubRepoName
  artifactFileName:
    Value:
      Fn::GetAtt: [codebuild, Outputs.artifactFileName]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-artifactFileName