---
AWSTemplateFormatVersion: '2010-09-09'
Description: api

Parameters:
  masterapi:
    Type: String
    Default: 3c379kpo75
  masterresource:
    Type: String
    Default: r10kgs
  deploybucket:
    Type: String
    Default: deploy-forms-larkin
  deployment:
    Type: String
    Default: pevgj9


Resources:
  LocalAPI:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["", ["https://s3.amazonaws.com/",!Ref deploybucket, "/forms/awsoptions/Includes/transform.yml"]]
      Parameters:
        masterapi: !Ref masterapi
        masterresource: !Ref masterresource
        deploybucket: !Ref deploybucket
        deployment: !Ref deployment