---
AWSTemplateFormatVersion: '2010-09-09'
Description: api

Parameters:
  masterapi:
    Type: String
    Default: czd0rqky4b
  masterresource:
    Type: String
    Default: rwf69r
  deploybucket:
    Type: String
    Default: deploy-forms-larkin


Resources:
  Type: "AWS::CloudFormation::Stack"
  Properties:
    TemplateURL: !Sub "s3://${deploybucket}/forms/awsoptions/Includes/transform.yml"