---
AWSTemplateFormatVersion: '2010-09-09'
Description: api

Parameters:
  masterapi:
    Type: String
    Default: czd0rqky4b
  masterresource:
    Type: String
    Default: rwf69r
  deploybucket:
    Type: String
    Default: deploy-forms-larkin


Resources:
  LocalAPI:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join ["", ["s3://",!Ref deploybucket, "/forms/awsoptions/Includes/transform.yml"]]