---
AWSTemplateFormatVersion: '2010-09-09'
Description: role

Parameters:
  roleServiceList:
    Type: CommaDelimitedList
  policyActionList:
    Type: CommaDelimitedList

Resources:
  role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal: 
              Service:
                !Ref roleServiceList
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: !Ref "AWS::StackName"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  !Ref policyActionList
                Resource: "*"

  CloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
  Account:
    Type: "AWS::ApiGateway::Account"
    Properties:
      CloudWatchRoleArn:
        "Fn::GetAtt":
          - CloudWatchRole
          - Arn

Outputs:
  roleName:
    Value: !Ref role
  roleArn:
    Value: !GetAtt role.Arn
  cwroleArn:
    Value: !GetAtt CloudWatchRole.Arn