---
AWSTemplateFormatVersion: '2010-09-09'
Description: s3

Parameters:
  s3CloudformationsBucket:
    Type: String
    Default: false

Resources:
    
  s3:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: AuthenticatedRead

Outputs:
  s3Name:
    Value: !Ref s3
