---
AWSTemplateFormatVersion: '2010-09-09'
Description: sqs
Resources:
  sqs:
    Type: "AWS::SQS::Queue"
    
Outputs:
  sqsArn:
    Value: !GetAtt sqs.Arn
  sqsName:
    Value: !GetAtt sqs.QueueName

