AWSTemplateFormatVersion: '2010-09-09'
Description: local api

Parameters:
  masterapi:
    Type: String
    Default: false
  masterresource:
    Type: String
    Default: false
  deploybucket:
    Type: String
    Default: false
  deployment:
    Type: String
    Default: false

Resources:

  apiResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref masterapi
      ParentId: !Ref masterresource
      PathPart: provision

  apiGatewayMethodOptions:
    Type: "AWS::ApiGateway::Method"
    Properties:
      ResourceId: !Ref apiResource
      RestApiId: !Ref masterapi
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      MethodResponses:
      -
        StatusCode: 200
        ResponseParameters:
          "method.response.header.Access-Control-Allow-Origin": true
          "method.response.header.Access-Control-Allow-Headers": true
          "method.response.header.Access-Control-Allow-Methods": true
          "method.response.header.Access-Control-Allow-Credentials": true
      Integration:
        Type: MOCK
        RequestTemplates:
          "application/json": "{statusCode:200}"
        IntegrationResponses:
        -
          StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin": "'*'"
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            "method.response.header.Access-Control-Allow-Methods": "'OPTIONS,ANY'"
            "method.response.header.Access-Control-Allow-Credentials": "'false'"
          ResponseTemplates:
            "application/json": ""

  apiGatewayStageDev:
    DependsOn:
      - apiDeployment
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref deployment
      MethodSettings:
        -
          DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
      RestApiId: !Ref masterapi
      StageName: dev
  apiGatewayStageProd:
    DependsOn:
      - apiDeployment
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref apiDeployment
      MethodSettings:
        -
          DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
      RestApiId: !Ref masterapi
      StageName: prod
  apiGatewayTest:
    DependsOn:
      - apiDeployment
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref deployment
      MethodSettings:
        -
          DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
      RestApiId: !Ref masterapi
      StageName: test

